# Form implementation generated from reading ui file 'AccountCreation_StepOne.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as sql_db_connect
import AccountCreationUI_StepTwo


class Sign_Up_One_Form(QtWidgets.QWidget):
    def __init__(self, login_form):
        super().__init__()

        self.setGeometry(700, 400, 400, 200)
        self.setWindowTitle("Application Login")

        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.le_first_name = QtWidgets.QLineEdit()
        self.le_first_name.setObjectName("le_first_name")
        self.horizontalLayout.addWidget(self.le_first_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel()
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_last_name = QtWidgets.QLineEdit()
        self.le_last_name.setObjectName("le_last_name")
        self.horizontalLayout_2.addWidget(self.le_last_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.le_dob = QtWidgets.QLineEdit()
        self.le_dob.setObjectName("le_dob")
        self.horizontalLayout_3.addWidget(self.le_dob)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel()
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel()
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.le_username = QtWidgets.QLineEdit()
        self.le_username.setObjectName("le_username")
        self.horizontalLayout_4.addWidget(self.le_username)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel()
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.le_password_one = QtWidgets.QLineEdit()
        self.le_password_one.setObjectName("le_password_one")
        self.horizontalLayout_5.addWidget(self.le_password_one)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel()
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.le_password_two = QtWidgets.QLineEdit()
        self.le_password_two.setObjectName("le_password_two")
        self.horizontalLayout_6.addWidget(self.le_password_two)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_next_step = QtWidgets.QPushButton()
        self.btn_next_step.setObjectName("btn_next_step")
        self.horizontalLayout_7.addWidget(self.btn_next_step)
        self.label_username_invalid = QtWidgets.QLabel()
        self.label_username_invalid.setText("")
        self.label_username_invalid.setObjectName("label_username_invalid")
        self.horizontalLayout_7.addWidget(self.label_username_invalid)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setLayout(self.gridLayout)

        self.btn_next_step.clicked.connect(lambda: self.next_step(login_form))


    def next_step(self, login_form):
        first_name = self.le_first_name.text()
        last_name = self.le_last_name.text()
        dob = self.le_dob.text()
        username = self.le_username.text()
        password_one = self.le_password_one.text()
        password_two = self.le_password_two.text()

        username_query = "SELECT * FROM users WHERE username = '{}'".format(username)

        try:
            db_data = sql_db_connect.connect(
                host="127.0.0.1",
                port="9000",
                user="root",
                password="root",
                database="finance_tracker"
            )
            data_handle = db_data.cursor()

        except sql_db_connect.error as e:
            print('Connection Error')

        data_handle.execute(username_query)
        db_username_result = data_handle.fetchone()

        if db_username_result is not None:
            dlg = IncorrectUsernameDialog()
            dlg.exec()

            self.le_username.setText("")
            return

        if password_one != password_two:
            dlg = IncorrectPasswordsDialog()
            dlg.exec()

            self.le_password_one.setText("")
            self.le_password_two.setText("")
            return

        new_account_data = [first_name, last_name, dob, username, password_one]
        print("First Name = {}\nLast Name = {}\nDate of Birth = {}\nUsername = {}\nPassword = {}"
              .format(new_account_data[0], new_account_data[1], new_account_data[2],
                      new_account_data[3], new_account_data[4]))

        login_form.sign_up_window = AccountCreationUI_StepTwo.Ui_FinishAccountSetUp()
        login_form.sign_up_window.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "First, we need some information about you!"))
        self.label_2.setText(_translate("Form", "First name:"))
        self.label_3.setText(_translate("Form", "Last name:"))
        self.label_4.setText(_translate("Form", "Date of birth:"))
        self.label_5.setText(_translate("Form", "Now, some information about your new account!"))
        self.label_6.setText(_translate("Form", "Username:"))
        self.label_7.setText(_translate("Form", "Password:"))
        self.label_8.setText(_translate("Form", "Re-enter \nPassword:"))
        self.btn_next_step.setText(_translate("Form", "Next Step"))


class IncorrectPasswordsDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Mis-Match Passwords")
        QBtn = QtWidgets.QDialogButtonBox.StandardButton.Ok

        self.buttonBox = QtWidgets.QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)

        self.layout = QtWidgets.QVBoxLayout()
        message = QtWidgets.QLabel("The passwords you entered do not match.\n"
                                   "Please try again!")
        self.layout.addWidget(message)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)


class IncorrectUsernameDialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Username Taken")
        QBtn = QtWidgets.QDialogButtonBox.StandardButton.Ok

        self.buttonBox = QtWidgets.QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)

        self.layout = QtWidgets.QVBoxLayout()
        message = QtWidgets.QLabel("The username you entered is already in use.\n"
                                   "Please try again!")
        self.layout.addWidget(message)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Sign_Up_One_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
'''