# Form implementation generated from reading ui file 'AccountCreation_StepTwo.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FinishAccountSetUp(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.setGeometry(700, 400, 550, 300)
        self.setWindowTitle("Application Login")
        self.label_2 = QtWidgets.QLabel(parent=self)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self)
        self.label_4.setGeometry(QtCore.QRect(150, 180, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(parent=self)
        self.pushButton.setGeometry(QtCore.QRect(190, 230, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=self)
        self.widget.setGeometry(QtCore.QRect(10, 10, 105, 73))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.rb_checking = QtWidgets.QRadioButton()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_checking.setFont(font)
        self.rb_checking.setObjectName("rb_checking")
        self.verticalLayout.addWidget(self.rb_checking)
        self.rb_savings = QtWidgets.QRadioButton()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_savings.setFont(font)
        self.rb_savings.setObjectName("rb_savings")
        self.verticalLayout.addWidget(self.rb_savings)
        self.widget1 = QtWidgets.QWidget(parent=self)
        self.widget1.setGeometry(QtCore.QRect(10, 90, 135, 49))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.le_startBalance = QtWidgets.QLineEdit(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_startBalance.setFont(font)
        self.le_startBalance.setObjectName("le_startBalance")
        self.verticalLayout_3.addWidget(self.le_startBalance)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setLayout(self.verticalLayout_3)

    def retranslateUi(self, FinishAccountSetUp):
        _translate = QtCore.QCoreApplication.translate
        FinishAccountSetUp.setWindowTitle(_translate("FinishAccountSetUp", "Finish Account Set-Up"))
        self.label_2.setText(_translate("FinishAccountSetUp", "The Financial Tracking Application is designed to assist you in managing your every day purchases and expenses. In order to get the most out of the application, try your best to use it frequently and to provide it with as accurate information as possible. The more details you can provide to the database, the more precisely it can predict your future account balances."))
        self.label_4.setText(_translate("FinishAccountSetUp", "OK, are we ready to begin?"))
        self.pushButton.setText(_translate("FinishAccountSetUp", "Create Account"))
        self.label.setText(_translate("FinishAccountSetUp", "Account Type:"))
        self.rb_checking.setText(_translate("FinishAccountSetUp", "Checkings"))
        self.rb_savings.setText(_translate("FinishAccountSetUp", "Savings"))
        self.label_3.setText(_translate("FinishAccountSetUp", "Starting Balance:"))
        self.le_startBalance.setText(_translate("FinishAccountSetUp", "0.00"))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FinishAccountSetUp = QtWidgets.QWidget()
    ui = Ui_FinishAccountSetUp()
    ui.setupUi(FinishAccountSetUp)
    FinishAccountSetUp.show()
    sys.exit(app.exec())
'''